name: dostx
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0+3

environment:
  sdk: ">=3.2.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3
  http: ^1.2.0
  dio: ^5.4.0
  retrofit: ^4.0.3
  bloc_provider: ^1.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http_parser: ^4.0.2
  intl: ^0.19.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  retrofit_generator: any
  json_model: any
  json_serializable: ^6.1.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/image/dostxbg.png
    - assets/image/dostxbg2.png
    - assets/image/emo_wheel.png
    - assets/image/Icon0.png
    - assets/image/Icon1.png
    - assets/image/Icon2.png
    - assets/image/Icon3.png
    - assets/image/Image-1.png
    - assets/image/Image-12.png
    - assets/p1.png
    - assets/p2.png
    - assets/image/02-square.png
    - assets/svg/ppp.svg
    - assets/svg/grandfather.svg
    - assets/svg/logo.svg
    - assets/image/logo.png
    - assets/svg/Group1.svg
    - assets/svg/02.svg
    - assets/svg/Group2.svg
    - assets/svg/Group4.svg
    - assets/svg/dostX_logo.svg
    - assets/svg/Icon-2.svg
    - assets/svg/Icon-3.svg
    - assets/svg/Icon-4.svg
    - assets/svg/Icon-5.svg
    - assets/svg/Icon-6.svg
    - assets/svg/Icon-7.svg
    - assets/svg/Icon-8.svg
    - assets/svg/Icon-9.svg
    - assets/svg/Icon-10.svg
    - assets/svg/Icon-11.svg
    - assets/svg/Icon-12.svg
    - assets/svg/Image-1.svg
    - assets/svg/Image-2.svg
    - assets/svg/Image-3.svg
    - assets/svg/Image-4.svg
    - assets/svg/Image-5.svg
    - assets/svg/Image-6.svg
    - assets/svg/Image-7.svg
    - assets/svg/Image-8.svg
    - assets/svg/Image-9.svg
    - assets/svg/Image-10.svg
    - assets/svg/image-11.svg
    - assets/svg/Image-12.svg
    - assets/svg/logo.svg
    - assets/svg/logoa1.svg
    - assets/svg/logo2.svg
    - assets/svg/lang.svg
    - assets/svg/grandma.svg
    - assets/svg/aunty.svg
    - assets/svg/logoa99.svg
    - assets/svg/Image.svg
    - assets/angry-selected.svg
    - assets/smiley-selected.svg
    - assets/hooo-selected.svg
    - assets/sad-selected.svg
    - assets/angry-unselected.svg
    - assets/smiley-unselected.svg
    - assets/hooo-unselected.svg
    - assets/sad-unselected.svg
    - assets/profile.png
    - assets/svg/emotional_wheel.svg
    - assets/image/canvas.png
    - assets/svg/DocIcon.svg
    - assets/image/med (1).png
    - assets/image/med (2).png
    - assets/image/med (3).png
    - assets/image/med (4).png
    - assets/image/coping (1).png
    - assets/image/coping (2).png
    - assets/image/coping (3).png
    - assets/image/coping (4).png
    - assets/svg/Icon tick.svg
    - assets/image/02-image.png



  #    -

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: JostSemi
      fonts:
        - asset: fonts/Jost/static/Jost-SemiBold.ttf
    - family: JostLightItalic
      fonts:
        - asset: fonts/Jost/static/Jost-LightItalic.ttf
    - family: JostMedium
      fonts:
        - asset: fonts/Jost/static/Jost-Medium.ttf
    - family: JostBold
      fonts:
        - asset: fonts/Jost/static/Jost-Bold.ttf
    - family: SFProText
      fonts:
        - asset: fonts/SF_Pro/static/SF-Pro-Text-Regular.ttf
    - family: SFProSemiBold
      fonts:
        - asset: fonts/SF_Pro/static/SF-Pro-Text-Semibold.ttf
    - family: SFProMedium
      fonts:
        - asset: fonts/SF_Pro/static/SF-Pro-Text-Medium.ttf
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular_684471b5ff3c204b8d3b3da3bd4e082d.ttf
    - family: LatoBold
      fonts:
        - asset: fonts/Lato/Lato-Bold.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-VariableFont_wght.ttf

          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
